// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TapSale.Web.Data;

#nullable disable

namespace TapSale.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803224029_ShiftNamesAndHistory")]
    partial class ShiftNamesAndHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TapSale.Web.Models.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("TapSale.Web.Models.CashShift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CountedClosingCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleListId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleListId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CashShift");
                });

            modelBuilder.Entity("TapSale.Web.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SaleListId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TapSale.Web.Models.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("SaleListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleListId", "Name")
                        .IsUnique();

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("TapSale.Web.Models.ProductPriceVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("ProductPriceVersion");
                });

            modelBuilder.Entity("TapSale.Web.Models.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OriginalSaleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SoldDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SoldDateUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TenderedCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CashShiftId");

                    b.HasIndex("OriginalSaleId");

                    b.HasIndex("SaleListId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("TapSale.Web.Models.SaleLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineTotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLine");
                });

            modelBuilder.Entity("TapSale.Web.Models.SaleList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryDisplayMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaleList");
                });

            modelBuilder.Entity("TapSale.Web.Models.UserSaleList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleListId");

                    b.HasIndex("UserId", "SaleListId")
                        .IsUnique();

                    b.ToTable("UserSaleList");
                });

            modelBuilder.Entity("TapSale.Web.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("TapSale.Web.Models.CashShift", b =>
                {
                    b.HasOne("TapSale.Web.Models.SaleList", "SaleList")
                        .WithMany()
                        .HasForeignKey("SaleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TapSale.Web.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapSale.Web.Models.Product", b =>
                {
                    b.HasOne("TapSale.Web.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TapSale.Web.Models.SaleList", "SaleList")
                        .WithMany("Products")
                        .HasForeignKey("SaleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("SaleList");
                });

            modelBuilder.Entity("TapSale.Web.Models.ProductCategory", b =>
                {
                    b.HasOne("TapSale.Web.Models.SaleList", "SaleList")
                        .WithMany("Categories")
                        .HasForeignKey("SaleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleList");
                });

            modelBuilder.Entity("TapSale.Web.Models.ProductPriceVersion", b =>
                {
                    b.HasOne("TapSale.Web.Models.Product", "Product")
                        .WithMany("Versions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TapSale.Web.Models.Sale", b =>
                {
                    b.HasOne("TapSale.Web.Models.CashShift", "CashShift")
                        .WithMany("Sales")
                        .HasForeignKey("CashShiftId");

                    b.HasOne("TapSale.Web.Models.Sale", "OriginalSale")
                        .WithMany()
                        .HasForeignKey("OriginalSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TapSale.Web.Models.SaleList", "SaleList")
                        .WithMany()
                        .HasForeignKey("SaleListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TapSale.Web.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashShift");

                    b.Navigation("OriginalSale");

                    b.Navigation("SaleList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapSale.Web.Models.SaleLine", b =>
                {
                    b.HasOne("TapSale.Web.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TapSale.Web.Models.Sale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("TapSale.Web.Models.UserSaleList", b =>
                {
                    b.HasOne("TapSale.Web.Models.SaleList", "SaleList")
                        .WithMany("Users")
                        .HasForeignKey("SaleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TapSale.Web.Models.AppUser", "User")
                        .WithMany("SaleLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapSale.Web.Models.UserSession", b =>
                {
                    b.HasOne("TapSale.Web.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapSale.Web.Models.AppUser", b =>
                {
                    b.Navigation("SaleLists");
                });

            modelBuilder.Entity("TapSale.Web.Models.CashShift", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("TapSale.Web.Models.Product", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TapSale.Web.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TapSale.Web.Models.Sale", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TapSale.Web.Models.SaleList", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
